import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('db', {
  login: (username, password) => ipcRenderer.invoke('db:login', { username, password }),
  getUsers: () => ipcRenderer.invoke('db:getUsers'),
  addUser: (name, email, password) => ipcRenderer.invoke('db:addUser', { name, email, password }),
  getSettings: () => ipcRenderer.invoke('db:getSettings'),
  updateSettings: (payload) => ipcRenderer.invoke('db:updateSettings', payload),
  getDashboardStats: () => ipcRenderer.invoke('db:getDashboardStats'),
  getProducts: (filters) => ipcRenderer.invoke('db:getProducts', filters),
  addProduct: (payload) => ipcRenderer.invoke('db:addProduct', payload),
  updateProduct: (payload) => ipcRenderer.invoke('db:updateProduct', payload),
  deleteProduct: (id) => ipcRenderer.invoke('db:deleteProduct', { id }),
  setProductActive: (id, isActive) => ipcRenderer.invoke('db:setProductActive', { id, isActive }),
  getCustomers: (filters) => ipcRenderer.invoke('db:getCustomers', filters),
  addCustomer: (payload) => ipcRenderer.invoke('db:addCustomer', payload),
  updateCustomer: (payload) => ipcRenderer.invoke('db:updateCustomer', payload),
  deleteCustomer: (id) => ipcRenderer.invoke('db:deleteCustomer', { id }),
  setCustomerActive: (id, isActive) =>
    ipcRenderer.invoke('db:setCustomerActive', { id, isActive }),
  getOrders: () => ipcRenderer.invoke('db:getOrders'),
  getOrderItems: (orderId) => ipcRenderer.invoke('db:getOrderItems', { orderId }),
  addOrder: (payload) => ipcRenderer.invoke('db:addOrder', payload),
  updateOrderStatus: (payload) => ipcRenderer.invoke('db:updateOrderStatus', payload),
  deleteOrder: (orderId) => ipcRenderer.invoke('db:deleteOrder', { orderId }),
  getOrderTracking: (orderId) => ipcRenderer.invoke('db:getOrderTracking', { orderId }),
  getPaymentOrders: (filters) => ipcRenderer.invoke('db:getPaymentOrders', filters),
  getOrderPaymentSummary: (orderId) => ipcRenderer.invoke('db:getOrderPaymentSummary', { orderId }),
  getPaymentsByOrder: (orderId) => ipcRenderer.invoke('db:getPaymentsByOrder', { orderId }),
  addPayment: (payload) => ipcRenderer.invoke('db:addPayment', payload),
  getAuditLogs: () => ipcRenderer.invoke('db:getAuditLogs'),
  getOrderReport: (filters) => ipcRenderer.invoke('db:getOrderReport', filters),
  saveFile: (payload) => ipcRenderer.invoke('file:save', payload),
  saveExcel: (payload) => ipcRenderer.invoke('file:saveExcel', payload),
  savePdf: (payload) => ipcRenderer.invoke('file:savePdf', payload),
  savePdfFromHtml: (payload) => ipcRenderer.invoke('file:savePdfFromHtml', payload),
  print: () => ipcRenderer.invoke('file:print'),
  printHtml: (payload) => ipcRenderer.invoke('file:printHtml', payload),
  printPreview: (payload) => ipcRenderer.invoke('file:printPreview', payload),
});
